# Generated by Django 5.2.9 on 2025-12-15 05:19

import apps.post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_postimage_active_postimage_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(default='post/default/post-default.png', upload_to=apps.post.models.get_image_filename),
        ),
    ]
